MPC-Controller:
  General:
    timesteps: 12
    sample_time: 0.1

  Initial-State:
    x: -8.0
    y: 0.7
    theta: -0.6
    linear-velocity: 0.0
    angular-velocity: 0.0
    throttle: 0.0

  # Model will try to stay close to these values
  Desired:
    velocity: 0.5
    cross_track_error: 0.0
    orientation_error: 0.0

  # Constraints
  Max-Bounds:
    omega: 2.0
    throttle: 1.0

  Weights:
    w_cte: 97.533213
    w_etheta: 0.157830
    w_vel: 0.514243
    w_omega: 0.121092
    w_acc: 0.085428
    w_omega_d: 0.114417
    w_acc_d: 0.344230

  # Termination conditions, loop ends when errors are within tolerance
  Teardown-Tolerance:
    velocity: 0.0001
    cross_track_error: 0.0001
    orientation_error: 0.0001
